# Municipal governance report generator (AREE v2.2)
# 4-page PDF via reportlab. Deterministic values only.

import io
from datetime import datetime, timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)

from config import (
    PERSISTENCE_THRESHOLD, HIGH_AQI_THRESHOLD,
    WINDOW_DURATION_MINUTES, WINDOW_HOP_MINUTES,
    HYSTERESIS_CONFIRMATIONS, VULNERABILITY_MULTIPLIERS,
    DEFAULT_IMPACT_RADIUS_KM, DEFAULT_EST_POPULATION,
    AQI_POLL_INTERVAL,
)

# colors
NAVY       = HexColor("#0f172a")
SLATE_DARK = HexColor("#1e293b")
SLATE      = HexColor("#334155")
SLATE_MED  = HexColor("#475569")
SLATE_LT   = HexColor("#94a3b8")
WHITE      = HexColor("#ffffff")
OFFWHITE   = HexColor("#f8fafc")
ACCENT     = HexColor("#2563eb")
RED        = HexColor("#dc2626")
AMBER      = HexColor("#d97706")
GREEN      = HexColor("#16a34a")
BORDER     = HexColor("#cbd5e1")

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 6)
    canvas.setFillColor(SLATE_LT)
    y = 10 * mm
    canvas.drawString(MARGIN, y,
        "AREE v2.2  |  Pathway Streaming  |  WAQI Direct  |  Satellite Verified  |  Live Policy Index")
    canvas.drawRightString(PAGE_W - MARGIN, y,
        f"Page {doc.page}  |  Generated by Deterministic Escalation Engine")
    canvas.restoreState()


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("rpt_title", fontSize=15, leading=19,
            textColor=NAVY, fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=2),
        "subtitle": ParagraphStyle("rpt_sub", fontSize=9, leading=12,
            textColor=SLATE_MED, fontName="Helvetica", alignment=TA_CENTER, spaceAfter=3),
        "timestamp": ParagraphStyle("rpt_ts", fontSize=7, leading=10,
            textColor=SLATE_LT, fontName="Helvetica", alignment=TA_CENTER, spaceAfter=6),
        "section": ParagraphStyle("rpt_sec", fontSize=11, leading=14,
            textColor=NAVY, fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4),
        "subsection": ParagraphStyle("rpt_ssec", fontSize=9, leading=12,
            textColor=SLATE_DARK, fontName="Helvetica-Bold", spaceBefore=6, spaceAfter=2),
        "body": ParagraphStyle("rpt_body", fontSize=8, leading=11,
            textColor=SLATE_DARK, fontName="Helvetica"),
        "mono": ParagraphStyle("rpt_mono", fontSize=7.5, leading=10,
            textColor=NAVY, fontName="Courier"),
        "note": ParagraphStyle("rpt_note", fontSize=7, leading=9,
            textColor=SLATE_MED, fontName="Helvetica-Oblique", spaceAfter=4),
        "label": base["Normal"],
    }


def _sec_header(text, sty):
    return [
        Spacer(1, 2 * mm),
        HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=3),
        Paragraph(text, sty["section"]),
    ]


def _kv_table(pairs, col1=50*mm, col2=110*mm):
    sty = _styles()
    rows = []
    for k, v in pairs:
        rows.append([
            Paragraph(f'<b>{k}</b>', ParagraphStyle("kl", fontSize=8, textColor=SLATE_MED, fontName="Helvetica-Bold")),
            Paragraph(str(v), ParagraphStyle("kv", fontSize=8, textColor=NAVY, fontName="Helvetica")),
        ])
    t = Table(rows, colWidths=[col1, col2])
    t.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 2.5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2.5),
        ('LINEBELOW', (0,0), (-1,-1), 0.25, BORDER),
    ]))
    return t


def _data_table(header, rows, col_widths=None):
    data = [header] + rows
    if not col_widths:
        n = len(header)
        col_widths = [(PAGE_W - 2*MARGIN) / n] * n
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), SLATE_DARK),
        ('TEXTCOLOR', (0,0), (-1,0), WHITE),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 7.5),
        ('TOPPADDING', (0,0), (-1,-1), 3),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ('GRID', (0,0), (-1,-1), 0.25, BORDER),
        ('ALIGN', (1,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    return t


def _box_block(elements_list):
    inner = Table([[e] for e in elements_list], colWidths=[PAGE_W - 2*MARGIN - 8*mm])
    inner.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, SLATE),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    return inner


def generate_escalation_report(station_key, state_snapshot, carbon_state=None):
    s = state_snapshot
    sty = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=14*mm, bottomMargin=16*mm,
    )

    els = []
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    aqi = s.get("aqi", 0)
    band = s.get("cpcb_band", "N/A")
    consec = s.get("consecutive_windows", 0)
    remaining = s.get("remaining_windows", 0)
    fc = s.get("forecast") or {}
    proj30 = fc.get("projected_30min", aqi)

    if consec >= PERSISTENCE_THRESHOLD:
        eng_mode = "TRIGGERED"
    elif consec > 0:
        eng_mode = "WATCH"
    else:
        eng_mode = "NORMAL"

    stale_sec = s.get("stale_seconds")
    freshness = f"{int(stale_sec / 60)} min" if stale_sec else "Live"

    # PAGE 1 - Executive Summary
    els.append(Paragraph("AUTONOMOUS REGULATORY ESCALATION ENGINE", sty["title"]))
    els.append(Paragraph("Municipal Situation Brief", sty["subtitle"]))
    els.append(Paragraph("Internal Governance Use", sty["subtitle"]))
    els.append(Paragraph(f"Generated: {now_utc}", sty["timestamp"]))
    els.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceAfter=8))

    # A. Decision Snapshot
    els.extend(_sec_header("A. Decision Snapshot", sty))
    snapshot_box = _box_block([
        Paragraph(f'<font size="9" color="#475569"><b>Station:</b></font>  '
                  f'<font size="10" color="#0f172a"><b>{station_key}</b></font>', sty["body"]),
        Spacer(1, 2*mm),
        Paragraph(f'<font size="9" color="#475569"><b>WAQI AQI:</b></font>  '
                  f'<font size="18" color="#0f172a"><b>{aqi}</b></font>  '
                  f'<font size="9" color="#475569">({band})</font>', sty["body"]),
        Spacer(1, 1*mm),
        Paragraph(f'<font size="9" color="#475569"><b>GRAP Stage:</b></font>  '
                  f'<font size="10" color="#0f172a"><b>{s.get("grap_stage", "N/A")}</b></font>', sty["body"]),
        Spacer(1, 1*mm),
        Paragraph(f'<font size="9" color="#475569"><b>Data Freshness:</b></font>  '
                  f'<font size="9" color="#0f172a">{freshness}</font>  |  '
                  f'<font size="9" color="#475569"><b>Timestamp:</b></font>  '
                  f'<font size="9" color="#0f172a">{s.get("waqi_timestamp", "N/A")}</font>', sty["body"]),
    ])
    els.append(snapshot_box)

    # B. Action Classification
    els.extend(_sec_header("B. Immediate Action Classification", sty))
    mode_label = {"NORMAL": "NORMAL OPERATIONS", "WATCH": "ESCALATION WATCH",
                  "TRIGGERED": "ESCALATION TRIGGERED"}[eng_mode]
    mode_hex = {"NORMAL": "#16a34a", "WATCH": "#d97706", "TRIGGERED": "#dc2626"}[eng_mode]

    if aqi >= HIGH_AQI_THRESHOLD:
        reason = f"AQI {aqi} exceeds threshold ({HIGH_AQI_THRESHOLD}). {consec}/{PERSISTENCE_THRESHOLD} qualifying windows sustained."
    else:
        reason = f"AQI {aqi} below threshold ({HIGH_AQI_THRESHOLD}). No qualifying high windows."

    els.append(Paragraph(f'<font size="12" color="{mode_hex}"><b>{mode_label}</b></font>', sty["body"]))
    els.append(Spacer(1, 1*mm))
    els.append(Paragraph(f'<font size="8" color="#475569"><b>Reason:</b> {reason}</font>', sty["body"]))

    # C. Short-Term Outlook
    els.extend(_sec_header("C. Short-Term Risk Outlook (30 Minutes)", sty))
    if fc:
        els.append(_kv_table([
            ("30-min Projected AQI", str(proj30)),
            ("Predicted GRAP Stage", fc.get("predicted_grap_30min", "N/A")),
            ("Trend Direction", fc.get("direction", "N/A").upper()),
            ("Rate of Change", f'{fc.get("rate_per_min", "N/A")} AQI/min'),
            ("Escalation ETA", f'{fc.get("escalation_eta", "N/A")} min' if fc.get("escalation_eta") else "No imminent escalation"),
            ("Exposure Score (30min)", str(fc.get("exposure_score_30min", "N/A"))),
            ("Anomaly Flag", "YES" if fc.get("anomaly") else "NO"),
        ]))
        els.append(Paragraph(
            f'Projection Method: Linear regression over last {fc.get("data_points", "N")} '
            f'sliding windows (slope: {fc.get("slope", "N/A")}).', sty["note"]))
    else:
        els.append(Paragraph("Insufficient data for projection.", sty["body"]))

    # D. Vulnerable Population Risk
    els.extend(_sec_header("D. Vulnerable Population Risk Matrix", sty))
    vr = s.get("vulnerable_risk", {})
    if vr:
        group_names = {"general": "General Public", "elderly": "Elderly (60+)",
                       "children": "Children (<14)", "respiratory": "Respiratory/Asthma"}
        vuln_rows = []
        for group, label in group_names.items():
            v = vr.get(group, {})
            vuln_rows.append([label, f'x{v.get("multiplier", 1.0)}',
                              str(v.get("score", 0)), v.get("level", "N/A").upper()])

        els.append(_data_table(
            ["Population Group", "Multiplier", "Projected Score", "Risk Category"],
            vuln_rows, col_widths=[50*mm, 25*mm, 35*mm, 30*mm],
        ))
        els.append(Spacer(1, 2*mm))
        els.append(Paragraph(
            "Risk Category Rule:  <100 LOW  |  100-200 MODERATE  |  200-300 HIGH  |  >300 SEVERE",
            sty["note"]))
        els.append(Paragraph(
            f'Impact Radius: {DEFAULT_IMPACT_RADIUS_KM} km  |  '
            f'Est. Population: {DEFAULT_EST_POPULATION:,} (placeholder)',
            sty["note"]))
    else:
        els.append(Paragraph("VPPE data not available yet.", sty["body"]))

    # E. Satellite Attribution
    els.extend(_sec_header("E. Satellite Transport Attribution", sty))
    fire_count = s.get("fire_count", 0)
    if fire_count > 0:
        els.append(_kv_table([
            ("Fire Hotspots", str(fire_count)),
            ("High Confidence Fires", str(s.get("high_conf_fires", 0))),
            ("Transport Score", f'{s.get("transport_score", 0)}/100'),
            ("Wind Speed", f'{s.get("wind_speed", "N/A")} m/s' if s.get("wind_speed") else "N/A"),
            ("Wind Direction", f'{s.get("wind_direction", "N/A")}deg' if s.get("wind_direction") else "N/A"),
            ("Attribution Label", s.get("transport_label", "N/A")),
            ("Confidence", f'{s.get("confidence_score", 0)}%'),
        ]))
    else:
        els.append(Paragraph(
            "No upwind thermal anomalies detected. Local emission dominant.", sty["body"]))
        els.append(_kv_table([
            ("Transport Score", f'{s.get("transport_score", 0)}/100'),
            ("Confidence", f'{s.get("confidence_score", 0)}%'),
            ("FIRMS Dataset", s.get("firms_dataset", "N/A")),
        ]))

    # Pre-emptive advisory
    pa = s.get("preemptive_advisory", [])
    if pa:
        els.append(Spacer(1, 3*mm))
        els.append(Paragraph('<font color="#dc2626"><b>PRE-EMPTIVE PUBLIC HEALTH ADVISORY</b></font>', sty["body"]))
        for item in pa:
            els.append(Paragraph(f'<font color="#0f172a">  - {item}</font>', sty["body"]))

    # PAGE 2 - Technical Detail
    els.append(PageBreak())
    els.append(Paragraph("TECHNICAL ESCALATION DETAIL", sty["title"]))
    els.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceAfter=8))

    # A. Pollutant Snapshot
    els.extend(_sec_header("A. Real-Time Pollutant Snapshot", sty))
    poll_map = [
        ("PM2.5", "raw_pm25"), ("PM10", "raw_pm10"), ("NO2", "raw_no2"),
        ("SO2", "raw_so2"), ("O3", "raw_o3"), ("CO", "raw_co"),
    ]
    poll_rows = []
    for name, key in poll_map:
        val = s.get(key)
        poll_rows.append([name, str(val) if val is not None else "--",
                          "Received" if val is not None else "Not available"])
    els.append(_data_table(["Pollutant", "Value", "Status"], poll_rows,
                           col_widths=[40*mm, 40*mm, 50*mm]))
    els.append(Spacer(1, 2*mm))
    els.append(Paragraph(
        f'Dominant Pollutant: {s.get("dominant_pollutant", "N/A")}  |  '
        f'Pollutants Available: {s.get("pollutants_available", 0)}/6', sty["note"]))

    # B. Engine Logic
    els.extend(_sec_header("B. Escalation Engine Logic", sty))
    trigger_rule = (
        f"Trigger Rule:\n"
        f"  AQI >= {HIGH_AQI_THRESHOLD}\n"
        f"  {PERSISTENCE_THRESHOLD} Consecutive Windows\n"
        f"  {WINDOW_DURATION_MINUTES}min Sliding  |  {WINDOW_HOP_MINUTES}min Hop\n"
        f"  Hysteresis: {HYSTERESIS_CONFIRMATIONS} confirmations"
    )
    els.append(_box_block([Paragraph(trigger_rule.replace('\n', '<br/>'), sty["mono"])]))

    # C. Persistence
    els.extend(_sec_header("C. Persistence State", sty))
    els.append(_kv_table([
        ("Current GRAP Stage", s.get("grap_stage", "N/A")),
        ("GRAP Description", s.get("grap_description", "N/A")),
        ("Consecutive High Windows", f"{consec}/{PERSISTENCE_THRESHOLD}"),
        ("Remaining to Trigger", str(remaining)),
        ("Projected Trigger Time", s.get("projected_trigger_time", "N/A")),
        ("Engine Mode", eng_mode),
    ]))

    # D. Decision Trace
    els.extend(_sec_header("D. Decision Trace", sty))
    trace = (
        f"Input AQI: {aqi}\n"
        f"Threshold: {HIGH_AQI_THRESHOLD}\n"
        f"Persistence: {consec}/{PERSISTENCE_THRESHOLD}\n"
        f"Hysteresis: {HYSTERESIS_CONFIRMATIONS} confirmations required\n"
        f"Escalation: {'TRIGGERED' if consec >= PERSISTENCE_THRESHOLD else 'Not triggered'}\n"
        f"Stage: {s.get('grap_stage', 'N/A')}"
    )
    els.append(_box_block([Paragraph(trace.replace('\n', '<br/>'), sty["mono"])]))

    # E. Predictive Detail
    els.extend(_sec_header("E. Predictive Intelligence Detail", sty))
    if fc:
        els.append(_kv_table([
            ("5-min Projected AQI", str(fc.get("projected_5min", "N/A"))),
            ("30-min Projected AQI", str(fc.get("projected_30min", "N/A"))),
            ("Trend Slope", str(fc.get("slope", "N/A"))),
            ("Trend Direction", fc.get("direction", "N/A").upper()),
            ("Rate of Change", f'{fc.get("rate_per_min", "N/A")} AQI/min'),
            ("Predicted GRAP (5min)", fc.get("predicted_grap", "N/A")),
            ("Predicted GRAP (30min)", fc.get("predicted_grap_30min", "N/A")),
            ("Exposure Score (30min)", str(fc.get("exposure_score_30min", "N/A"))),
            ("Anomaly Detected", "YES" if fc.get("anomaly") else "NO"),
            ("Data Points Used", str(fc.get("data_points", 0))),
            ("Poll Interval", f"{AQI_POLL_INTERVAL}s"),
        ]))
    else:
        els.append(Paragraph("Needs 3+ sliding windows.", sty["body"]))

    # F. ERI Summary
    els.extend(_sec_header("F. Escalation Readiness Summary", sty))
    eri = s.get("eri_score", 0)
    eri_cat = s.get("eri_category", "LOW READINESS")
    eri_factors = s.get("eri_factors", [])
    els.append(_kv_table([("ERI Score", f'{eri}/100'), ("Readiness Category", eri_cat)]))
    if eri_factors:
        els.append(Spacer(1, 2*mm))
        els.append(Paragraph('<b>Contributing Factors:</b>', sty["body"]))
        for f in eri_factors:
            els.append(Paragraph(f'  - {f}', sty["body"]))
    els.append(Spacer(1, 2*mm))
    els.append(Paragraph(
        'ERI is advisory only. Does not affect GRAP trigger logic.',
        sty["note"]))

    # G. Regional Snapshot
    els.extend(_sec_header("G. Regional Comparative Snapshot", sty))
    from app import latest_state as _all_st
    _act = {k: v for k, v in _all_st.items()
            if isinstance(v, dict) and v.get("aqi") is not None and v.get("status") != "DATA_INVALID"}
    n_stations = len(_act)
    if n_stations >= 1:
        aqi_rank = sorted(_act.items(), key=lambda x: x[1].get("aqi", 0), reverse=True)
        eri_rank = sorted(_act.items(), key=lambda x: x[1].get("eri_score", 0), reverse=True)
        aqi_pos = next((i+1 for i, (k, _) in enumerate(aqi_rank) if k == station_key), "N/A")
        eri_pos = next((i+1 for i, (k, _) in enumerate(eri_rank) if k == station_key), "N/A")
        els.append(_kv_table([
            ("Total Stations", str(n_stations)),
            ("AQI Rank", f"#{aqi_pos} of {n_stations}"),
            ("ERI Rank", f"#{eri_pos} of {n_stations}"),
        ]))
        top3 = aqi_rank[:3]
        top_rows = [[stn, str(v.get("aqi", 0)), str(v.get("eri_score", 0))] for stn, v in top3]
        if top_rows:
            els.append(Spacer(1, 3*mm))
            els.append(Paragraph("<b>Top Stations by AQI</b>", sty["body"]))
            els.append(_data_table(["Station", "AQI", "ERI"], top_rows,
                                   col_widths=[60*mm, 35*mm, 35*mm]))
    else:
        els.append(Paragraph("No cross-station data yet.", sty["body"]))

    # PAGE 3 - Policy Grounding
    els.append(PageBreak())
    els.append(Paragraph("POLICY CONTEXT AND LEGAL BASIS", sty["title"]))
    els.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceAfter=8))

    els.extend(_sec_header("A. Policy Retrieval Metadata", sty))
    els.append(_kv_table([
        ("Source Document", s.get("rag_policy_file", "N/A")),
        ("Similarity Score", str(s.get("rag_similarity_score", 0))),
        ("Documents Indexed", str(s.get("rag_docs_indexed", 0))),
        ("Index Type", s.get("rag_index_type", "N/A")),
        ("Embedding Model", s.get("rag_embed_model", "N/A")),
        ("Last Sync", s.get("rag_last_updated", "N/A")),
    ]))

    els.extend(_sec_header("B. Governance Protocol", sty))
    els.append(Paragraph(
        f'<font size="8" color="#0f172a">{s.get("governance_rule", "N/A")}</font>', sty["body"]))

    els.append(Spacer(1, 6*mm))
    els.append(Paragraph(
        'This advisory references policy documents retrieved via Pathway DocumentStore '
        '(live indexed). Similarity scores reflect vector retrieval proximity only and '
        'do not imply legal enforcement.', sty["note"]))

    # PAGE 4 - System Transparency
    els.append(PageBreak())
    els.append(Paragraph("SYSTEM TRANSPARENCY AND AUDITABILITY", sty["title"]))
    els.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT, spaceAfter=8))

    els.extend(_sec_header("A. Data Source Provenance", sty))
    els.append(_kv_table([
        ("WAQI Feed ID", s.get("feed_id", "N/A")),
        ("WAQI Timestamp", s.get("waqi_timestamp", "N/A")),
        ("API Response Time", s.get("api_time", "N/A")),
        ("Data Freshness", freshness),
        ("Station (API Name)", s.get("station_name_api", "N/A")),
        ("Ingestion Status", s.get("ingestion_status", "N/A")),
    ]))

    els.extend(_sec_header("B. Model Description", sty))
    els.append(_kv_table([
        ("Predictive Model", "Linear regression (numpy.polyfit, degree 1)"),
        ("Embedding Model", s.get("rag_embed_model", "all-MiniLM-L6-v2")),
        ("RAG Pipeline", "Pathway DocumentStore (BruteForceKnnFactory, 384-dim)"),
        ("Satellite Dataset", s.get("firms_dataset", "VIIRS_SNPP_NRT")),
        ("Anomaly Detection", "Z-score threshold (>2 sigma)"),
    ]))

    els.extend(_sec_header("C. Engine Configuration", sty))
    els.append(_kv_table([
        ("Sliding Window", f"{WINDOW_DURATION_MINUTES} min duration, {WINDOW_HOP_MINUTES} min hop"),
        ("Persistence Threshold", f"{PERSISTENCE_THRESHOLD} consecutive windows"),
        ("Hysteresis Confirmations", str(HYSTERESIS_CONFIRMATIONS)),
        ("AQI Threshold", str(HIGH_AQI_THRESHOLD)),
        ("Poll Interval", f"{AQI_POLL_INTERVAL}s"),
    ]))

    els.extend(_sec_header("D. Carbon Accounting", sty))
    if carbon_state:
        els.append(_kv_table([
            ("Total Emissions", f'{carbon_state.get("total_gco2", 0)} gCO2eq'),
            ("Decisions Processed", str(carbon_state.get("decision_count", 0))),
            ("Per-Decision Emission", f'{carbon_state.get("per_decision_gco2", 0)} gCO2eq'),
        ]))
    else:
        els.append(Paragraph("Carbon data not available.", sty["body"]))

    els.extend(_sec_header("E. Report Metadata", sty))
    els.append(_kv_table([
        ("Report Generated (UTC)", now_utc),
        ("Engine Version", "AREE v2.2"),
        ("Architecture", "Pathway xLLM | Single-Process DocumentStore"),
        ("LLM Content in Report", "NONE - Deterministic only"),
    ]))

    els.append(Spacer(1, 8*mm))
    els.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    els.append(Spacer(1, 2*mm))
    els.append(Paragraph(
        'This document contains no generative narrative. All values are deterministic '
        'outputs from live system state.',
        sty["note"]))

    doc.build(els, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
